### ISSUE TITLE
Mythril build error

### ISSUE THREAD

**Issue by Ferparishuertas** [BlockChainCompany/solhydra#2]
Solhydra execution fails on mythril image build
Setting up libedit2:amd64 (3.1-20150325-1ubuntu2) ...
Setting up libxmuu1:amd64 (2:1.1.2-2) ...
Setting up openssh-client (1:7.2p2-4ubuntu2.4) ...
Setting up rsync (3.1.1-3ubuntu1.2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up xauth (1:1.0.9-1ubuntu2) ...
Setting up liberror-perl (0.17-1.2) ...
Setting up git-man (1:2.7.4-0ubuntu1.3) ...
Setting up git (1:2.7.4-0ubuntu1.3) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.2) ...
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
ERROR: Service 'mythril' failed to build: The command '/bin/sh -c apt-get update   && apt-get install -y software-properties-common python-software-properties curl   && add-apt-repository ppa:ethereum/ethereum   && apt-get update   && apt-get install -y solc   && apt-get install -y libssl-dev   && apt-get install -y python3-pip python3-dev   && ln -s /usr/bin/python3 /usr/local/bin/python   && pip3 install --upgrade pip   && apt-get install -y pandoc   && apt-get install -y git   && pip3 install laser-ethereum   && pip3 install mythril   && curl --create-dirs -o ~/.mythril/signatures.json https://raw.githubusercontent.com/b-mueller/mythril/master/signatures.json   && curl -sL https://deb.nodesource.com/setup_8.x | bash -   && apt-get install -y nodejs' returned a non-zero code: 1

ERROR

 Error: exited with error code: 1
    at ChildProcess.child.on.code (/usr/local/lib/node_modules/solhydra/lib/index.js:296:39)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by rmi7** [comment]
working on it

**Comment by rmi7** [comment]
fixed in https://github.com/BlockChainCompany/solhydra/commit/b19f2aef20b80c64b1a3ef9a29cd1ec1e1b5917f
